apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: mobile-backend
build:
  local:
    useBuildkit: false
  artifacts:
    - image: auth-api
      context: .
      docker:
        dockerfile: apps/auth-api/Dockerfile
manifests:
  kustomize:
    paths:
      - infra/k8s/overlays/local
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: auth-api-service
    namespace: mobile-backend
    port: 3000
    localPort: 3000
